### ISSUE TITLE
when I try socat -h , nothing happen

### ISSUE THREAD

**Issue by tlsalex** [valorisa/socat-1.7.4.3-for-Windows#3]
Hi man,

I am not sure if I am correct , I have downloaded socat-1.7.4.3.rar , and extracted it , then copy socat.exe into C:\Windows\System32\ folder , then I tried below , nothing happen , did I miss something?  
`
PS C:\Windows\System32> .\socat.exe -h`

**Comment by tlsalex** [comment]
My laptop is running Windows10 21H2

**Comment by valorisa** [comment]
Hello,
Have you tried extract to a different place like 'C:\Program Files\' ?

**Comment by valorisa** [comment]
![IMG20220605182431](https://user-images.githubusercontent.com/13067566/172060581-96a0fcc1-75e5-45bd-a0b9-fea5643ba26b.jpg)

**Comment by valorisa** [comment]
Try with 'socat -h' and not './socat -h'.

**Comment by valorisa** [comment]
![IMG20220605183455](https://user-images.githubusercontent.com/13067566/172060836-7c087729-d9d8-421a-adde-e1045ea03f04.jpg)

**Comment by valorisa** [comment]
> My laptop is running Windows10 21H2

Here Windows 11 Pro Insider Preview 22H2

**Comment by valorisa** [comment]
> Hi man,
> 
> I am not sure if I am correct , I have downloaded socat-1.7.4.3.rar , and extracted it , then copy socat.exe into C:\Windows\System32\ folder , then I tried below , nothing happen , did I miss something? ` PS C:\Windows\System32> .\socat.exe -h`

Copy the directory totally and not only 'socat.exe'.

**Comment by tlsalex** [comment]
thanks so much @valorisa

**Comment by TBX3D** [comment]
I would suggest extract the whole thing in program files, and make sure cygwin is in your path. (set PATH=%PATH%;C:\cygwin64\bin)

also install dependencies

thank you so much by the way
